server:
  port: 8088
spring:
  mvc:
    view:
      prefix : /WEB-INF/views/
      suffix : .jsp
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/dh-answer?serverTimezone=GMT%2B8
    username: root
    password: 123456
  redis:
    host: 127.0.0.1
    port: 6379
  thymeleaf: 
    prefix: classpath:/static/
#spring 扫描实体类路径
mybatis:
  type-aliases-package: com.answer.api.entity
  mapper-locations: classpath*:mapper/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
#mybatis-plus
mybatis-plus.mapper-locations: classpath*:mapper/*.xml
mybatis-plus.type-aliases-package: com.answer.api.entity
mybatis-plus.configuration.map-underscore-to-camel-case: true
mybatis-plus.configuration.log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

#微信相关配置
WeiXin:
  appId: wx5d449646cc1713fb
  appSecret: cf769f4c9b4a6c75af5209a8da6ed331