server:
  port: 6377
  address: 0.0.0.0
  ssl:
    key-store: classpath:4889133_www.superdaheng.com.pfx
    key-store-password: zn51C4VO
    key-store-type: PKCS12

spring:
  mvc:
    view:
      prefix : /WEB-INF/views/
      suffix : .jsp
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://47.112.187.145:3306/dh-answer?serverTimezone=GMT%2B8
    username: root
    password: NnjFarEY3EwShkBj
  redis:
    host: 127.0.0.1
    port: 6379
    testOnBorrow: true
  thymeleaf: 
    prefix: classpath:/static/
    
logging:
  pattern:
    console: "%d - %msg%n"
  file:
    name: /www/wwwroot/logs/answer.log
#spring 扫描实体类路径
mybatis:
  type-aliases-package: com.answer.api.entity
  mapper-locations: classpath*:mapper/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
#mybatis-plus
mybatis-plus.mapper-locations: classpath*:mapper/*.xml
mybatis-plus.type-aliases-package: com.answer.api.entity
mybatis-plus.configuration.map-underscore-to-camel-case: true
mybatis-plus.configuration.log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
#微信相关配置
WeiXin:
  appId: wx5d449646cc1713fb
  appSecret: cf769f4c9b4a6c75af5209a8da6ed331
